using SAPbobsCOM;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DefaultWebProject.Enum;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace DefaultWebProject.Models
{
    [Table("OCRD")]
    public class BlinkModel
    {
        //public string AdicionarPnEnum { get; set; }
        //public string BANCO { get; set; }

        [Key]
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public string CardType { get; set; }
        public Int16 GroupCode { get; set; }
        public string CmpPrivate { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public string MailAddres { get; set; }
        public string MailZipCod { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Fax { get; set; }
        public string CntctPrsn { get; set; }
        public string Notes { get; set; }
        public decimal Balance { get; set; }
        public decimal? ChecksBal { get; set; }
        public decimal? DNotesBal { get; set; }
        public decimal? OrdersBal { get; set; }
        public Int16? GroupNum { get; set; }
        public decimal? CreditLine { get; set; }
        public decimal? DebtLine { get; set; }
        public decimal? Discount { get; set; }
        public string VatStatus { get; set; }
        public string LicTradNum { get; set; }
        public string DdctStatus { get; set; }
        public decimal? DdctPrcnt { get; set; }
        public DateTime? ValidUntil { get; set; }
        public int? Chrctrstcs { get; set; }
        public int? ExMatchNum { get; set; }
        public int? InMatchNum { get; set; }
        public Int16? ListNum { get; set; }
        public decimal? DNoteBalFC { get; set; }
        public decimal? OrderBalFC { get; set; }
        public decimal? DNoteBalSy { get; set; }
        public decimal? OrderBalSy { get; set; }
        public string Transfered { get; set; }
        public string BalTrnsfrd { get; set; }
        public decimal? IntrstRate { get; set; }
        public decimal? Commission { get; set; }
        public Int16? CommGrCode { get; set; }
        public string Free_Text { get; set; }
        public int? SlpCode { get; set; }
        public string PrevYearAc { get; set; }
        public string Currency { get; set; }
        public string RateDifAct { get; set; }
        public decimal? BalanceSys { get; set; }
        public decimal? BalanceFC { get; set; }
        public string Protected { get; set; }
        public string Cellular { get; set; }
        public Int16? AvrageLate { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string Country { get; set; }
        public string MailCity { get; set; }
        public string MailCounty { get; set; }
        public string MailCountr { get; set; }
        public string E_Mail { get; set; }
        public string Picture { get; set; }
        public string DflAccount { get; set; }
        public string DflBranch { get; set; }
        public string BankCode { get; set; }
        public string AddID { get; set; }
        public string Pager { get; set; }
        public string FatherCard { get; set; }
        public string CardFName { get; set; }
        public string FatherType { get; set; }
        public string DdctOffice { get; set; }
         public DateTime? CreateDate { get; set; }
        public DateTime? UpdateDate { get; set; }
        public string ExportCode { get; set; }
        public Int16? DscntObjct { get; set; }
        public string DscntRel { get; set; }
        public Int16? SPGCounter { get; set; }
        public int? SPPCounter { get; set; }
        public string DdctFileNo { get; set; }
        public Int16? SCNCounter { get; set; }
        public decimal? MinIntrst { get; set; }
        public string DataSource { get; set; }
        public int? OprCount { get; set; }
        public string ExemptNo { get; set; }
        public int? Priority { get; set; }
        public Int16? CreditCard { get; set; }
        public string CrCardNum { get; set; }
        public DateTime? CardValid { get; set; }
        public Int16? UserSign { get; set; }
        public string LocMth { get; set; }
        public string validFor { get; set; }
         public DateTime? validFrom { get; set; }
         public DateTime? validTo { get; set; }
        public string frozenFor { get; set; }
        public DateTime? frozenFrom { get; set; }
        public DateTime? frozenTo { get; set; }
       public string sEmployed { get; set; }
        public int? MTHCounter { get; set; }
        public int? BNKCounter { get; set; }
        public int? DdgKey { get; set; }
        public int? DdtKey { get; set; }
        public string ValidComm { get; set; }
        public string FrozenComm { get; set; }
        public string chainStore { get; set; }
        public string DiscInRet { get; set; }
        public string State1 { get; set; }
        public string State2 { get; set; }
        public string VatGroup { get; set; }
        public int? LogInstanc { get; set; }
        public string ObjType { get; set; }
        public string Indicator { get; set; }
        public Int16? ShipType { get; set; }
        public string DebPayAcct { get; set; }
        public string ShipToDef { get; set; }
        public string Block { get; set; }
        public string MailBlock { get; set; }
        public string Password { get; set; }
        public string ECVatGroup { get; set; }
        public string Deleted { get; set; }
        public string IBAN { get; set; }
        public int? DocEntry { get; set; }
        public int? FormCode { get; set; }
        public string Box1099 { get; set; }
        public string PymCode { get; set; }
        public string BackOrder { get; set; }
        public string PartDelivr { get; set; }
        public int? DunnLevel { get; set; }
         public DateTime? DunnDate { get; set; }
        public string BlockDunn { get; set; }
        public string BankCountr { get; set; }
        public string CollecAuth { get; set; }
        public string DME { get; set; }
        public string InstrucKey { get; set; }
        public string SinglePaym { get; set; }
        public string ISRBillId { get; set; }
        public string PaymBlock { get; set; }
        public string RefDetails { get; set; }
        public string HouseBank { get; set; }
        public string OwnerIdNum { get; set; }
        public int? PyBlckDesc { get; set; }
        public string HousBnkCry { get; set; }
        public string HousBnkAct { get; set; }
        public string HousBnkBrn { get; set; }
        public string ProjectCod { get; set; }
        public int? SysMatchNo { get; set; }
        public string VatIdUnCmp { get; set; }
        public string AgentCode { get; set; }
        public Int16? TolrncDays { get; set; }
        public string SelfInvoic { get; set; }
        public string DeferrTax { get; set; }
        public string LetterNum { get; set; }
        public decimal? MaxAmount { get; set; }
         public DateTime? FromDate { get; set; }
        public DateTime? ToDate { get; set; }
        public string WTLiable { get; set; }
        public string CrtfcateNO { get; set; }
          public DateTime? ExpireDate { get; set; }
        public string NINum { get; set; }
        public string AccCritria { get; set; }
        public string WTCode { get; set; }
        public string Equ { get; set; }
        public string HldCode { get; set; }
        public string ConnBP { get; set; }
        public int? MltMthNum { get; set; }
        public string TypWTReprt { get; set; }
        public string VATRegNum { get; set; }
        public string RepName { get; set; }
        public string Industry { get; set; }
        public string Business { get; set; }
        public string WTTaxCat { get; set; }
        public string IsDomestic { get; set; }
        public string IsResident { get; set; }
        public string AutoCalBCG { get; set; }
        public string OtrCtlAcct { get; set; }
        public string AliasName { get; set; }
        public string Building { get; set; }
        public string MailBuildi { get; set; }
        public string BoEPrsnt { get; set; }
        public string BoEDiscnt { get; set; }
        public string BoEOnClct { get; set; }
        public string UnpaidBoE { get; set; }
        public string ITWTCode { get; set; }
        public string DunTerm { get; set; }
        public string ChannlBP { get; set; }
        public int? DfTcnician { get; set; }
        public int? Territory { get; set; }
        public string BillToDef { get; set; }
        public string DpmClear { get; set; }
        public string IntrntSite { get; set; }
        public int? LangCode { get; set; }
        public int HousActKey { get; set; }
        public string Profession { get; set; }
        public Int16? CDPNum { get; set; }
        public int? DflBankKey { get; set; }
        public string BCACode { get; set; }
        public string UseShpdGd { get; set; }
        public string RegNum { get; set; }
        public string VerifNum { get; set; }
        public string BankCtlKey { get; set; }
        public string HousCtlKey { get; set; }
        public string AddrType { get; set; }
        public string InsurOp347 { get; set; }
        public string MailAddrTy { get; set; }
        public string StreetNo { get; set; }
        public string MailStrNo { get; set; }
        public string TaxRndRule { get; set; }
        public int? VendTID { get; set; }
        public string ThreshOver { get; set; }
        public string SurOver { get; set; }
        public string VendorOcup { get; set; }
        public string OpCode347 { get; set; }
        public string DpmIntAct { get; set; }
        public string ResidenNum { get; set; }
        public Int16? UserSign2 { get; set; }
        public string PlngGroup { get; set; }
        public string VatIDNum { get; set; }
        public string Affiliate { get; set; }
        public string MivzExpSts { get; set; }
        public string HierchDdct { get; set; }
        public string CertWHT { get; set; }
        public string CertBKeep { get; set; }
        public string WHShaamGrp { get; set; }
        public int? IndustryC { get; set; }
        public string DatevAcct { get; set; }
        public string DatevFirst { get; set; }
        public string GTSRegNum { get; set; }
        public string GTSBankAct { get; set; }
        public string GTSBilAddr { get; set; }
        public string HsBnkSwift { get; set; }
        public string HsBnkIBAN { get; set; }
        public string DflSwift { get; set; }
        public string AutoPost { get; set; }
        public string IntrAcc { get; set; }
        public string FeeAcc { get; set; }
        public int? CpnNo { get; set; }
        public Int16? NTSWebSite { get; set; }
        public string DflIBAN { get; set; }
        public int? Series { get; set; }
        public int? Number { get; set; }
        public int? EDocExpFrm { get; set; }
        public string TaxIdIdent { get; set; }
        public string Attachment { get; set; }
        public int? AtcEntry { get; set; }
        public string DiscRel { get; set; }
        public string NoDiscount { get; set; }
        public string SCAdjust { get; set; }
        public int? DflAgrmnt { get; set; }
        public string GlblLocNum { get; set; }
        public string SenderID { get; set; }
        public string RcpntID { get; set; }
        public int? MainUsage { get; set; }
        public string SefazCheck { get; set; }
        public string free312 { get; set; }
        public string free313 { get; set; }
         public DateTime? DateFrom { get; set; }
         public DateTime? DateTill { get; set; }
        public string RelCode { get; set; }
        public string OKATO { get; set; }
        public string OKTMO { get; set; }
        public string KBKCode { get; set; }
        public string TypeOfOp { get; set; }
        public int? OwnerCode { get; set; }
        public int? MandateID { get; set; }
        public DateTime? SignDate { get; set; }
        public int? Remark1 { get; set; }
        public string ConCerti { get; set; }
        public int? TpCusPres { get; set; }
        public string RoleTypCod { get; set; }
        public string BlockComm { get; set; }
        public string EmplymntCt { get; set; }
        public string ExcptnlEvt { get; set; }
        public decimal? ExpnPrfFnd { get; set; }
        public string EdrsFromBP { get; set; }
        public string EdrsToBP { get; set; }
        public int? CreateTS { get; set; }
        public int? UpdateTS { get; set; }
        public string EDocGenTyp { get; set; }
        public string eStreet { get; set; }
        public string eStreetNum { get; set; }
        public int? eBuildnNum { get; set; }
        public string eZipCode { get; set; }
        public string eCityTown { get; set; }
        public string eCountry { get; set; }
        public string eDistrict { get; set; }
        public string RepFName { get; set; }
        public string RepSName { get; set; }
        public string RepCmpName { get; set; }
        public string RepFisCode { get; set; }
        public string RepAddID { get; set; }
        public string PECAddr { get; set; }
        public string IPACodePA { get; set; }
        public string PriceMode { get; set; }
        public string EffecPrice { get; set; }
        public string TxExMxVdTp { get; set; }
        public string MerchantID { get; set; }
        public string UseBilAddr { get; set; }
        public string NaturalPer { get; set; }
        public string DPPStatus { get; set; }
        public string EnAddID { get; set; }
        public string EncryptIV { get; set; }
        public string EnDflAccnt { get; set; }
        public string EnDflIBAN { get; set; }
        public string EnERD4In { get; set; }
        public string EnERD4Out { get; set; }
        public string U_TranspDfl { get; set; }
        public string U_RBH_Contrib { get; set; }
        public int? U_ReleaseInstallment { get; set; }
        public string U_UPWhsCod { get; set; }
        public string U_UPNFRtSC { get; set; }
        public int? U_UPD_Teste { get; set; }
        public string U_Latitude { get; set; }
        public string U_Longitude { get; set; }
        public string U_UPD_PCK_TRSP { get; set; }
        public decimal? U_SIEBS_DescBole { get; set; }
        public string U_SIEBS_FaturPN { get; set; }
        public string U_SIEBS_CodeGrpEmp { get; set; }
        public string U_UPD_BPClass { get; set; }



        //public string fantasia { get; set; }
        //public string cnpj { get; set; }
        //public string inscricaoEstadual { get; set; }
        //public DateTime dataCadastro { get; set; }
        //public string email { get; set; }
        //public string emailNfe { get; set; }
        //public string ativo { get; set; }
        //public int codigoCondicaoPagamento { get; set; }
        //public string codigoFormaPagamento { get; set; }
        //public string codigoTabelaPreco { get; set; }
        //public string codigoTipoPedido { get; set; }
        //public double percentualDesconto { get; set; }
        //public string dataUltimaVisita { get; set; }
        //public string dataUltimaCompra { get; set; }
        //public int codigoGrupo { get; set; }
        //public string canal { get; set; }
        //public string endereco { get; set; }
        //public string numero { get; set; }
        //public string complemento { get; set; }
        //public string bairro { get; set; }
        //public string cidade { get; set; }
        //public string estado { get; set; }
        //public string cep { get; set; }
        //public string telefone { get; set; }
        //public string fax { get; set; }
        //public double limiteCredito { get; set; }
        //public double creditoDisponivel { get; set; }
        //public string ramoAtividade { get; set; }
        //public string pais { get; set; }
        //public string moeda { get;  set; }
        //public string companiaPrivada { get;  set; }
        //public int GrupoComissao { get;  set; }
        //public double comissaoPercentual { get;  set;}
        //public string contatoPessoal { get;  set; }
        //public string VatLiable { get;  set; }
        //public int tipoEnvio {get;  set; }
        //public int series {get;  set; }
        //public string SUBJECT {get; set; }

    }

}
